### ISSUE TITLE
Implémenter la messagerie dans Pawdirecte

### ISSUE THREAD

**Issue by camarm-dev** [camarm-dev/Pawdirecte#3]
Implémenter la messagerie Ecoledirecte dans Pawdirecte

Statut:
- [ ] ~~Envoyer des messages~~
- [x] Lister les messages
- [x] Lire les messages
- [x] Pièces jointes

**Comment by imyanice** [comment]
besoin de quelqu'un d'autre pour faire l'envoie des messages

**Comment by camarm-dev** [comment]
On va faire passer ça en partie 1... On verra plus tard pour l'envoi de messages
